services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword!123"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "StrongPassword!123" -C -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend/Workforce.Api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=WorkforceCompetenceDb;User Id=sa;Password=StrongPassword!123;TrustServerCertificate=True"
    ports:
      - "5080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "8088:80"
    depends_on:
      - api
