using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workforce.Api.Migrations;

public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "Competences", columns: table => new { Id = table.Column<int>(type: "int", nullable: false).Annotation("SqlServer:Identity", "1, 1"), Name = table.Column<string>(type: "nvarchar(max)", nullable: false), Category = table.Column<string>(type: "nvarchar(max)", nullable: false) }, constraints: table => { table.PrimaryKey("PK_Competences", x => x.Id); });
        migrationBuilder.CreateTable(name: "Employees", columns: table => new { Id = table.Column<int>(type: "int", nullable: false).Annotation("SqlServer:Identity", "1, 1"), Name = table.Column<string>(type: "nvarchar(max)", nullable: false), Role = table.Column<string>(type: "nvarchar(max)", nullable: false), Department = table.Column<string>(type: "nvarchar(max)", nullable: false), Authorization = table.Column<string>(type: "nvarchar(max)", nullable: true), PositionPercent = table.Column<decimal>(type: "decimal(5,2)", precision: 5, scale: 2, nullable: false), MaxWeeklyHours = table.Column<decimal>(type: "decimal(5,2)", precision: 5, scale: 2, nullable: false), IsActive = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => { table.PrimaryKey("PK_Employees", x => x.Id); });
        migrationBuilder.CreateTable(name: "AuditEvents", columns: table => new { Id = table.Column<long>(type: "bigint", nullable: false).Annotation("SqlServer:Identity", "1, 1"), OccurredAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false), Action = table.Column<string>(type: "nvarchar(max)", nullable: false), EntityType = table.Column<string>(type: "nvarchar(max)", nullable: false), EntityId = table.Column<string>(type: "nvarchar(max)", nullable: false), Actor = table.Column<string>(type: "nvarchar(max)", nullable: true), Reason = table.Column<string>(type: "nvarchar(max)", nullable: true), DetailsJson = table.Column<string>(type: "nvarchar(max)", nullable: true) }, constraints: table => { table.PrimaryKey("PK_AuditEvents", x => x.Id); });
        migrationBuilder.CreateTable(name: "Shifts", columns: table => new { Id = table.Column<int>(type: "int", nullable: false).Annotation("SqlServer:Identity", "1, 1"), Date = table.Column<DateOnly>(type: "date", nullable: false), ShiftType = table.Column<string>(type: "nvarchar(max)", nullable: false), Department = table.Column<string>(type: "nvarchar(max)", nullable: false), StartTime = table.Column<TimeOnly>(type: "time", nullable: true), Hours = table.Column<decimal>(type: "decimal(4,2)", precision: 4, scale: 2, nullable: false), MinimumStaff = table.Column<int>(type: "int", nullable: false), IsPublished = table.Column<bool>(type: "bit", nullable: false), IsCritical = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => { table.PrimaryKey("PK_Shifts", x => x.Id); });
        migrationBuilder.CreateTable(name: "UserAccounts", columns: table => new { Id = table.Column<int>(type: "int", nullable: false).Annotation("SqlServer:Identity", "1, 1"), Username = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false), PasswordHash = table.Column<string>(type: "nvarchar(max)", nullable: false), Role = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false), IsActive = table.Column<bool>(type: "bit", nullable: false), FailedLoginAttempts = table.Column<int>(type: "int", nullable: false), LockedUntilUtc = table.Column<DateTime>(type: "datetime2", nullable: true), CreatedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false), LastLoginAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true), EmployeeId = table.Column<string>(type: "nvarchar(max)", nullable: true) }, constraints: table => { table.PrimaryKey("PK_UserAccounts", x => x.Id); });
        migrationBuilder.CreateTable(name: "Absences", columns: table => new { Id = table.Column<int>(type: "int", nullable: false).Annotation("SqlServer:Identity", "1, 1"), EmployeeId = table.Column<int>(type: "int", nullable: false), From = table.Column<DateOnly>(type: "date", nullable: false), To = table.Column<DateOnly>(type: "date", nullable: false), Type = table.Column<int>(type: "int", nullable: false), Note = table.Column<string>(type: "nvarchar(max)", nullable: true), Approved = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => { table.PrimaryKey("PK_Absences", x => x.Id); table.ForeignKey("FK_Absences_Employees_EmployeeId", x => x.EmployeeId, "Employees", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "EmployeeCompetences", columns: table => new { EmployeeId = table.Column<int>(type: "int", nullable: false), CompetenceId = table.Column<int>(type: "int", nullable: false), Level = table.Column<int>(type: "int", nullable: false), ValidUntil = table.Column<DateOnly>(type: "date", nullable: true) }, constraints: table => { table.PrimaryKey("PK_EmployeeCompetences", x => new { x.EmployeeId, x.CompetenceId }); table.ForeignKey("FK_EmployeeCompetences_Competences_CompetenceId", x => x.CompetenceId, "Competences", "Id", onDelete: ReferentialAction.Cascade); table.ForeignKey("FK_EmployeeCompetences_Employees_EmployeeId", x => x.EmployeeId, "Employees", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "ShiftAssignments", columns: table => new { ShiftId = table.Column<int>(type: "int", nullable: false), EmployeeId = table.Column<int>(type: "int", nullable: false) }, constraints: table => { table.PrimaryKey("PK_ShiftAssignments", x => new { x.ShiftId, x.EmployeeId }); table.ForeignKey("FK_ShiftAssignments_Employees_EmployeeId", x => x.EmployeeId, "Employees", "Id", onDelete: ReferentialAction.Cascade); table.ForeignKey("FK_ShiftAssignments_Shifts_ShiftId", x => x.ShiftId, "Shifts", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "ShiftRequirements", columns: table => new { ShiftId = table.Column<int>(type: "int", nullable: false), CompetenceId = table.Column<int>(type: "int", nullable: false), MinimumCount = table.Column<int>(type: "int", nullable: false), MinimumLevel = table.Column<int>(type: "int", nullable: false), RequiredRole = table.Column<string>(type: "nvarchar(max)", nullable: true), IsCritical = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => { table.PrimaryKey("PK_ShiftRequirements", x => new { x.ShiftId, x.CompetenceId }); table.ForeignKey("FK_ShiftRequirements_Competences_CompetenceId", x => x.CompetenceId, "Competences", "Id", onDelete: ReferentialAction.Cascade); table.ForeignKey("FK_ShiftRequirements_Shifts_ShiftId", x => x.ShiftId, "Shifts", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateIndex(name: "IX_Absences_EmployeeId_From_To", table: "Absences", columns: new[] { "EmployeeId", "From", "To" });
        migrationBuilder.CreateIndex(name: "IX_AuditEvents_OccurredAtUtc", table: "AuditEvents", column: "OccurredAtUtc");
        migrationBuilder.CreateIndex(name: "IX_Competences_Name", table: "Competences", column: "Name", unique: true);
        migrationBuilder.CreateIndex(name: "IX_EmployeeCompetences_CompetenceId", table: "EmployeeCompetences", column: "CompetenceId");
        migrationBuilder.CreateIndex(name: "IX_ShiftAssignments_EmployeeId", table: "ShiftAssignments", column: "EmployeeId");
        migrationBuilder.CreateIndex(name: "IX_ShiftRequirements_CompetenceId", table: "ShiftRequirements", column: "CompetenceId");
        migrationBuilder.CreateIndex(name: "IX_UserAccounts_Username", table: "UserAccounts", column: "Username", unique: true);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "Absences");
        migrationBuilder.DropTable(name: "AuditEvents");
        migrationBuilder.DropTable(name: "EmployeeCompetences");
        migrationBuilder.DropTable(name: "ShiftAssignments");
        migrationBuilder.DropTable(name: "ShiftRequirements");
        migrationBuilder.DropTable(name: "UserAccounts");
        migrationBuilder.DropTable(name: "Employees");
        migrationBuilder.DropTable(name: "Competences");
        migrationBuilder.DropTable(name: "Shifts");
    }
}
